#!/usr/bin/env bash
set -euo pipefail

usage() {
  cat <<'EOF'
Usage:
  local_codex_ssh.sh [options] [-- CODEX_ARGS...]

Run Codex locally while using a remote container for project shell commands.
The remote container does not need Codex installed.

Options:
  --config PATH         Config env file (default: ./config.env or CHISEL_HTTP_SSH_CONFIG)
  --host-alias NAME      SSH config host alias (default: worker-0-chisel)
  --remote-path PATH     Remote path to mount and work in (default: /public/home/tangyu408)
  --mount-point PATH     Local sshfs mount point (default: ./remote-home)
  --no-mount             Do not auto-mount; require mount point to already exist
  --no-network           Do not enable local command network access for the SSH tunnel
  --full-access          Start Codex with danger-full-access instead of workspace-write
  --sshfs-option OPTION  Extra sshfs -o option for auto-mount; can be repeated
  -h, --help             Show this help

Examples:
  bash local_codex_ssh.sh
  bash local_codex_ssh.sh -- --model gpt-5.5
EOF
}

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd -P)"
# shellcheck disable=SC1091
. "$SCRIPT_DIR/lib_chisel_config.sh"
CONFIG_FILE="$(chisel_config_file_from_args "$SCRIPT_DIR" "$@")"
chisel_load_config "$CONFIG_FILE"

HOST_ALIAS="${HOST_ALIAS:-worker-0-chisel}"
REMOTE_PATH="${REMOTE_PATH:-${REMOTE_HOME:-/public/home/tangyu408}}"
MOUNT_POINT="${MOUNT_POINT:-remote-home}"
AUTO_MOUNT="${AUTO_MOUNT:-1}"
ENABLE_NETWORK="${ENABLE_NETWORK:-1}"
SANDBOX_MODE="${CODEX_SANDBOX_MODE:-${SANDBOX_MODE:-workspace-write}}"
SSHFS_OPTIONS=()
CODEX_ARGS=()

while [ "$#" -gt 0 ]; do
  case "$1" in
    --host-alias) HOST_ALIAS="${2:?Missing value for --host-alias}"; shift 2 ;;
    --config) CONFIG_FILE="${2:?Missing value for --config}"; shift 2 ;;
    --config=*) CONFIG_FILE="${1#--config=}"; shift ;;
    --remote-path) REMOTE_PATH="${2:?Missing value for --remote-path}"; shift 2 ;;
    --mount-point) MOUNT_POINT="${2:?Missing value for --mount-point}"; shift 2 ;;
    --no-mount) AUTO_MOUNT="0"; shift ;;
    --no-network) ENABLE_NETWORK="0"; shift ;;
    --full-access) SANDBOX_MODE="danger-full-access"; shift ;;
    --sshfs-option) SSHFS_OPTIONS+=("${2:?Missing value for --sshfs-option}"); shift 2 ;;
    --) shift; CODEX_ARGS=("$@"); break ;;
    -h|--help) usage; exit 0 ;;
    *) echo "Unknown argument: $1" >&2; usage; exit 2 ;;
  esac
done

case "$MOUNT_POINT" in
  /*) ;;
  *) MOUNT_POINT="$PWD/$MOUNT_POINT" ;;
esac

log() {
  printf '[local-codex-ssh] %s\n' "$*"
}

is_mounted() {
  mountpoint -q "$1" 2>/dev/null || findmnt -M "$1" >/dev/null 2>&1
}

shell_quote() {
  printf "'%s'" "$(printf '%s' "$1" | sed "s/'/'\\\\''/g")"
}

toml_basic_string() {
  local value="$1"
  value="${value//\\/\\\\}"
  value="${value//\"/\\\"}"
  value="${value//$'\n'/\\n}"
  printf '"%s"' "$value"
}

if ! command -v codex >/dev/null 2>&1; then
  log "ERROR: local codex command is required."
  exit 1
fi

if ! command -v ssh >/dev/null 2>&1; then
  log "ERROR: local ssh command is required."
  exit 1
fi

if ! ssh -o BatchMode=yes "$HOST_ALIAS" "test -d $(shell_quote "$REMOTE_PATH")"; then
  log "ERROR: cannot reach $HOST_ALIAS or remote path does not exist: $REMOTE_PATH"
  log "Start local_start_chisel.sh first and verify: ssh $HOST_ALIAS"
  exit 1
fi

if is_mounted "$MOUNT_POINT"; then
  log "Mount already active: $MOUNT_POINT"
elif [ "$AUTO_MOUNT" = "1" ]; then
  mount_args=(
    --host-alias "$HOST_ALIAS"
    --remote-path "$REMOTE_PATH"
    --mount-point "$MOUNT_POINT"
  )
  for opt in "${SSHFS_OPTIONS[@]}"; do
    mount_args+=(--sshfs-option "$opt")
  done
  "$SCRIPT_DIR/local_mount_remote_home.sh" "${mount_args[@]}"
else
  log "ERROR: mount point is not mounted: $MOUNT_POINT"
  exit 1
fi

mkdir -p "$MOUNT_POINT/.codex"
install -m 0755 "$SCRIPT_DIR/local_remote_exec.sh" "$MOUNT_POINT/.codex/remote_exec"

{
  printf '# Generated by local_codex_ssh.sh. Used by .codex/remote_exec.\n'
  printf 'REMOTE_EXEC_HOST_ALIAS=%s\n' "$(shell_quote "$HOST_ALIAS")"
  printf 'REMOTE_EXEC_REMOTE_PATH=%s\n' "$(shell_quote "$REMOTE_PATH")"
  printf 'REMOTE_EXEC_MOUNT_POINT=%s\n' "$(shell_quote "$MOUNT_POINT")"
} > "$MOUNT_POINT/.codex/remote_exec.env"
chmod 600 "$MOUNT_POINT/.codex/remote_exec.env"

cat > "$MOUNT_POINT/.codex/REMOTE_EXECUTION.md" <<EOF
# Remote Execution Contract

Codex is running on the local machine. This directory is an sshfs mount of:

- SSH host: \`$HOST_ALIAS\`
- Remote path: \`$REMOTE_PATH\`
- Local mount: \`$MOUNT_POINT\`

Files read or written under the local mount affect the remote container through
sshfs. Project shell commands must run in the remote container through:

\`\`\`bash
./.codex/remote_exec --shell 'pwd && python -V'
./.codex/remote_exec -- pytest -q
\`\`\`

Do not run project build, test, install, or inspection commands directly on the
local machine.
EOF

remote_exec_path="$MOUNT_POINT/.codex/remote_exec"
developer_instructions=$(cat <<EOF
Remote execution contract for this session:
- Codex is running locally and communicates with OpenAI from the local machine.
- The working directory is an sshfs mount of $HOST_ALIAS:$REMOTE_PATH at $MOUNT_POINT.
- The remote container does not have Codex and must not be asked to install Codex.
- Read and edit files through the mounted workspace.
- Run project shell commands only through $remote_exec_path.
- For shell syntax, use $remote_exec_path --shell "COMMAND".
- For argv-style commands, use $remote_exec_path -- COMMAND ARGS.
- Do not run project build, test, install, or inspection commands directly on the local machine.
EOF
)

codex_cmd=(
  codex
  -C "$MOUNT_POINT"
  --sandbox "$SANDBOX_MODE"
  -c "developer_instructions=$(toml_basic_string "$developer_instructions")"
)

if [ "$SANDBOX_MODE" = "workspace-write" ] && [ "$ENABLE_NETWORK" = "1" ]; then
  codex_cmd+=(-c "sandbox_workspace_write.network_access=true")
fi

log "Installed remote command helper: $remote_exec_path"
log "Remote cwd test: $("${remote_exec_path}" --cwd "$MOUNT_POINT" --print-cwd)"
log "Starting local Codex in $MOUNT_POINT"

exec "${codex_cmd[@]}" "${CODEX_ARGS[@]}"
