#!/usr/bin/env bash
set -euo pipefail

# Generated by project-docker-runner for project: scnet_ssh_tracing
# Source behavior follows VisPrune docker/README.md and run_other_project_gpu.sh.

CUDA_VERSION="${CUDA_VERSION:-}"
CUDA_DEFAULT="${CUDA_DEFAULT:-${CUDA_VERSION:-system}}"
IMAGE_NAME="${IMAGE_NAME:-auto-research-gpu:cu128-cu129-cu130-cu132-torch}"
CUDA_SHORT="${CUDA_SHORT:-13.2}"
NODE_MAJOR="${NODE_MAJOR:-22}"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" >/dev/null 2>&1 && pwd -P)"
DEFAULT_PROJECT_DIR="$(cd -- "${SCRIPT_DIR}/.." >/dev/null 2>&1 && pwd -P)"
PROJECT_DIR="${PROJECT_DIR:-${DEFAULT_PROJECT_DIR}}"
PROJECT_NAME="${PROJECT_NAME:-$(basename "${PROJECT_DIR}")}"
CONTAINER_NAME="${CONTAINER_NAME:-${PROJECT_NAME}_dev}"

HOST_HOME="${HOST_HOME:-${HOME}}"
HOST_UID="${HOST_UID:-$(id -u)}"
HOST_GID="${HOST_GID:-$(id -g)}"
HOST_USER="${HOST_USER:-$(id -un)}"
HOST_GROUP="${HOST_GROUP:-$(id -gn)}"
CONTAINER_LOGIN_USER="${CONTAINER_LOGIN_USER:-root}"

DOCKER_CACHE_ROOT="${DOCKER_CACHE_ROOT:-/data3/docker_cache}"
CACHE_DIR="${CACHE_DIR:-${DOCKER_CACHE_ROOT}/${PROJECT_NAME}}"
CONTAINER_CACHE_DIR="${CONTAINER_CACHE_DIR:-${CACHE_DIR}}"
CONTAINER_HOME="${CONTAINER_HOME:-${HOST_HOME}}"
CONTAINER_HOME_CACHE_DIR="${CONTAINER_HOME_CACHE_DIR:-${CACHE_DIR}/home/${HOST_USER}}"
CONTAINER_HOST_HOME_DIR="${CONTAINER_HOST_HOME_DIR:-${CONTAINER_HOME}/.host-home}"
NPM_GLOBAL_DIR="${NPM_GLOBAL_DIR:-${CACHE_DIR}/npm-global}"
CONTAINER_NPM_GLOBAL_DIR="${CONTAINER_NPM_GLOBAL_DIR:-${CONTAINER_CACHE_DIR}/npm-global}"

DOCKER_MODEL_ROOT="${DOCKER_MODEL_ROOT:-/data3/docker_model}"
HOST_PROJ_MODEL_DIR="${HOST_PROJ_MODEL_DIR:-${DOCKER_MODEL_ROOT}/${PROJECT_NAME}}"
CONTAINER_PROJ_MODEL_DIR="${CONTAINER_PROJ_MODEL_DIR:-${HOST_PROJ_MODEL_DIR}}"
HOST_SHARED_MODEL_DIRS="${HOST_SHARED_MODEL_DIRS:-}"
CONTAINER_SHARED_MODEL_DIRS="${CONTAINER_SHARED_MODEL_DIRS:-}"

HOST_NVIDIA_DIR="${HOST_NVIDIA_DIR:-/opt/nvidia}"
CONTAINER_NVIDIA_DIR="${CONTAINER_NVIDIA_DIR:-/opt/nvidia}"
HOST_LOCAL_DIR="${HOST_LOCAL_DIR:-${HOST_HOME}/.local}"
CONTAINER_HOST_LOCAL_DIR="${CONTAINER_HOST_LOCAL_DIR:-${CONTAINER_HOST_HOME_DIR}/.local}"
HOST_PAPER_SKILLS_DIR="${HOST_PAPER_SKILLS_DIR:-/data3/paper_analysis/.claude/skills}"
CONTAINER_PAPER_SKILLS_DIR="${CONTAINER_PAPER_SKILLS_DIR:-${HOST_PAPER_SKILLS_DIR}}"

CLAUDE_CONFIG_MODE="${CLAUDE_CONFIG_MODE:-rw}"
CODEX_CONFIG_MODE="${CODEX_CONFIG_MODE:-rw}"
AGENTS_CONFIG_MODE="${AGENTS_CONFIG_MODE:-rw}"
ORCHESTRA_CONFIG_MODE="${ORCHESTRA_CONFIG_MODE:-rw}"
SKILL_SYMLINK_TARGET_MODE="${SKILL_SYMLINK_TARGET_MODE:-ro}"
ROOT_LOGIN_ACL="${ROOT_LOGIN_ACL:-1}"
ROOT_LOGIN_ACL_RECURSIVE="${ROOT_LOGIN_ACL_RECURSIVE:-1}"
HOST_SHARED_PERMISSION_REPAIR="${HOST_SHARED_PERMISSION_REPAIR:-1}"
RECREATE="${RECREATE:-0}"
ENABLE_FUSE="${ENABLE_FUSE:-1}"
FUSE_CAP_SYS_ADMIN="${FUSE_CAP_SYS_ADMIN:-1}"
FUSE_APPARMOR_UNCONFINED="${FUSE_APPARMOR_UNCONFINED:-1}"

case "${CONTAINER_LOGIN_USER}" in
  root|host) ;;
  *)
    echo "Unknown CONTAINER_LOGIN_USER: ${CONTAINER_LOGIN_USER}" >&2
    echo "Valid: root host" >&2
    exit 1
    ;;
esac

mkdir -p "${CACHE_DIR}"
if [ ! -w "${CACHE_DIR}" ]; then
  echo "Cache dir is not writable by ${HOST_USER}:${HOST_GROUP} (${HOST_UID}:${HOST_GID}): ${CACHE_DIR}" >&2
  echo "Please chown it or set CACHE_DIR to a writable path." >&2
  exit 1
fi

HOST_HOME_REAL="$(readlink -f -- "${HOST_HOME}")"
CONTAINER_HOME_CACHE_REAL="$(realpath -m -- "${CONTAINER_HOME_CACHE_DIR}")"

path_is_under() {
  local path="$1"
  local prefix="$2"

  [ "${path}" = "${prefix}" ] || [[ "${path}" == "${prefix}"/* ]]
}

reject_forbidden_home_cache() {
  if path_is_under "${CONTAINER_HOME_CACHE_REAL}" "${HOST_HOME_REAL}"; then
    echo "Refusing to use a host-home path as container HOME cache: ${CONTAINER_HOME_CACHE_DIR}" >&2
    echo "Set CONTAINER_HOME_CACHE_DIR outside ${HOST_HOME}." >&2
    exit 1
  fi
}

reject_forbidden_home_cache

mkdir -p \
  "${CONTAINER_HOME_CACHE_DIR}" \
  "${NPM_GLOBAL_DIR}" \
  "${CACHE_DIR}/xdg-cache" \
  "${HOST_PROJ_MODEL_DIR}"

write_container_user_bashrc() {
  local source_path="${HOST_HOME}/.bashrc"
  local target_path="${CONTAINER_HOME_CACHE_DIR}/.bashrc"
  local tmp_path="${target_path}.tmp"

  mkdir -p "$(dirname -- "${target_path}")"
  {
    echo "# Generated by project-docker-runner from Claude-related host .bashrc exports."
    if [ -f "${source_path}" ]; then
      awk '
        /^[[:space:]]*export[[:space:]]+(ANTHROPIC_|CLAUDE_CODE_|MAX_MCP_OUTPUT_TOKENS=)/ { print }
      ' "${source_path}"
    fi
    cat <<'BASHRC'

fix_host_agent_permissions() {
  [ "$(id -u)" = "0" ] || return 0
  [ -n "${HOST_UID:-}" ] && [ -n "${HOST_GID:-}" ] || return 0

  local path
  for path in \
    "${HOME}/.codex" \
    "${HOME}/.claude" \
    "${HOME}/.claude.json" \
    "${HOME}/.agents" \
    "${HOME}/.orchestra"
  do
    [ -e "${path}" ] || continue
    chown -h "${HOST_UID}:${HOST_GID}" "${path}" 2>/dev/null || true
    if [ -d "${path}" ]; then
      find "${path}" -xdev -uid 0 -exec chown -h "${HOST_UID}:${HOST_GID}" {} + 2>/dev/null || true
    fi
  done
}

fix_host_shared_permissions() {
  [ "$(id -u)" = "0" ] || return 0
  [ -n "${HOST_UID:-}" ] && [ -n "${HOST_GID:-}" ] || return 0

  local old_ifs="${IFS}"
  local path
  IFS=":"
  for path in ${HOST_SHARED_PERMISSION_PATHS:-}; do
    [ -n "${path}" ] && [ -e "${path}" ] || continue
    chown -h "${HOST_UID}:${HOST_GID}" "${path}" 2>/dev/null || true
    if [ -d "${path}" ]; then
      find "${path}" -xdev -uid 0 -exec chown -h "${HOST_UID}:${HOST_GID}" {} + 2>/dev/null || true
    fi
  done
  IFS="${old_ifs}"
}

_codex_with_host_permissions() {
  command codex --dangerously-bypass-approvals-and-sandbox "$@"
  local status=$?
  fix_host_agent_permissions
  return "${status}"
}

_claude_with_host_permissions() {
  command claude --dangerously-skip-permissions "$@"
  local status=$?
  fix_host_agent_permissions
  return "${status}"
}

alias codex='_codex_with_host_permissions'
alias claude='_claude_with_host_permissions'
fix_host_agent_permissions >/dev/null 2>&1 || true
BASHRC
  } > "${tmp_path}"
  mv -- "${tmp_path}" "${target_path}"
}

write_container_user_bashrc

SETFACL_MISSING_WARNED=0

grant_host_user_acl() {
  local path="$1"
  local recursive="${2:-${ROOT_LOGIN_ACL_RECURSIVE}}"

  if [ "${CONTAINER_LOGIN_USER}" != "root" ] || [ "${ROOT_LOGIN_ACL}" != "1" ] || [ ! -e "${path}" ]; then
    return
  fi
  if ! command -v setfacl >/dev/null 2>&1; then
    if [ "${HOST_SHARED_PERMISSION_REPAIR}" = "1" ]; then
      if [ "${SETFACL_MISSING_WARNED}" = "0" ]; then
        echo "Warning: setfacl is unavailable; relying on container-side shared permission repair." >&2
        SETFACL_MISSING_WARNED=1
      fi
      return
    fi
    echo "setfacl is required for CONTAINER_LOGIN_USER=root with ROOT_LOGIN_ACL=1." >&2
    echo "Install the host acl package, or set CONTAINER_LOGIN_USER=host." >&2
    exit 1
  fi

  if [ -d "${path}" ]; then
    if ! setfacl -m "u:${HOST_USER}:rwX,d:u:${HOST_USER}:rwX" "${path}" 2>/dev/null; then
      echo "Warning: unable to set ACL on ${path}; continuing." >&2
      return
    fi
    if [ "${recursive}" = "1" ]; then
      find "${path}" -type d -exec setfacl -m "u:${HOST_USER}:rwX,d:u:${HOST_USER}:rwX" {} + 2>/dev/null || true
      find "${path}" ! -type d ! -type l -exec setfacl -m "u:${HOST_USER}:rwX" {} + 2>/dev/null || true
    fi
  else
    setfacl -m "u:${HOST_USER}:rw" "${path}" 2>/dev/null || \
      echo "Warning: unable to set ACL on ${path}; continuing." >&2
  fi
}

grant_rw_mount_acl() {
  local path="$1"
  local mode="$2"
  local recursive="${3:-${ROOT_LOGIN_ACL_RECURSIVE}}"

  [[ ",${mode}," == *,ro,* ]] || grant_host_user_acl "${path}" "${recursive}"
}

grant_host_user_acl "${PROJECT_DIR}" "1"
grant_host_user_acl "${CACHE_DIR}" "1"
grant_host_user_acl "${CONTAINER_HOME_CACHE_DIR}" "1"
grant_host_user_acl "${NPM_GLOBAL_DIR}" "1"
grant_host_user_acl "${HOST_PROJ_MODEL_DIR}" "1"
grant_rw_mount_acl "${HOST_HOME}/.claude" "${CLAUDE_CONFIG_MODE}" "1"
grant_rw_mount_acl "${HOST_HOME}/.claude.json" "${CLAUDE_CONFIG_MODE}" "0"
grant_rw_mount_acl "${HOST_HOME}/.codex" "${CODEX_CONFIG_MODE}" "1"

warn_unreadable_codex_config() {
  local config_path="${HOST_HOME}/.codex/config.toml"

  [ -e "${config_path}" ] || return
  if [ ! -r "${config_path}" ]; then
    echo "Warning: ${config_path} is not readable by ${HOST_USER}." >&2
    echo "If a previous root container wrote it, repair it on the host with:" >&2
    echo "  sudo chown ${HOST_UID}:${HOST_GID} ${config_path} && chmod 600 ${config_path}" >&2
  fi
}

warn_unreadable_codex_config

build_nvidia_path_prefix() {
  local host_dir
  local rel_path
  local container_dir
  local path_prefix=""

  [ -d "${HOST_NVIDIA_DIR}" ] || return
  for host_dir in \
    "${HOST_NVIDIA_DIR}/bin" \
    "${HOST_NVIDIA_DIR}"/nsight-compute/* \
    "${HOST_NVIDIA_DIR}"/nsight-systems/*/bin
  do
    [ -d "${host_dir}" ] || continue
    rel_path="${host_dir#"${HOST_NVIDIA_DIR}"}"
    container_dir="${CONTAINER_NVIDIA_DIR}${rel_path}"
    path_prefix="${container_dir}${path_prefix:+:${path_prefix}}"
  done
  printf '%s\n' "${path_prefix}"
}

NVIDIA_PATH_PREFIX="$(build_nvidia_path_prefix)"
CUDA_PATH_PREFIX="/usr/local/cuda/bin"
if [ -n "${CUDA_SHORT}" ]; then
  CUDA_PATH_PREFIX="/usr/local/cuda-${CUDA_SHORT}/bin:${CUDA_PATH_PREFIX}"
fi

container_exists() {
  docker ps -a --format '{{.Names}}' | grep -Fxq "${CONTAINER_NAME}"
}

container_running() {
  docker ps --format '{{.Names}}' | grep -Fxq "${CONTAINER_NAME}"
}

if container_exists; then
  if [ "${RECREATE}" = "1" ]; then
    docker rm -f "${CONTAINER_NAME}"
  else
    if container_running; then
      echo "Container ${CONTAINER_NAME} is already running."
      echo "Attach with: docker exec -it ${CONTAINER_NAME} /bin/bash"
    else
      echo "Container ${CONTAINER_NAME} already exists but is stopped."
      echo "Start it with: docker start -ai ${CONTAINER_NAME}"
    fi
    echo "To recreate it with the mounts in this script, run:"
    echo "  RECREATE=1 $0"
    exit 1
  fi
fi

docker_args=(
  run
  -itd
  --name "${CONTAINER_NAME}"
  --gpus all
  --network host
  --ipc host
  --ulimit memlock=-1
  --ulimit stack=67108864
  -e HOME="${CONTAINER_HOME}"
  -e NVIDIA_VISIBLE_DEVICES=all
  -e NVIDIA_DRIVER_CAPABILITIES=all
  -e HF_HOME="${CONTAINER_CACHE_DIR}/huggingface"
  -e TORCH_HOME="${CONTAINER_CACHE_DIR}/torch"
  -e TRITON_CACHE_DIR="${CONTAINER_CACHE_DIR}/triton"
  -e XDG_CACHE_HOME="${CONTAINER_CACHE_DIR}/xdg-cache"
  -e NPM_CONFIG_PREFIX="${CONTAINER_NPM_GLOBAL_DIR}"
  -e PROJ_MODEL_DIR="${CONTAINER_PROJ_MODEL_DIR}"
  -e CODEX_HOME="${CONTAINER_HOME}/.codex"
  -e HOST_HOME_READONLY="${CONTAINER_HOST_HOME_DIR}"
  -e PATH="${NVIDIA_PATH_PREFIX:+${NVIDIA_PATH_PREFIX}:}${CONTAINER_HOST_LOCAL_DIR}/bin:${CONTAINER_NPM_GLOBAL_DIR}/bin:/opt/conda/bin:/opt/conda/condabin:${CUDA_PATH_PREFIX}:/usr/local/bin:/usr/bin:/bin"
  -e CUDA_DEFAULT="${CUDA_DEFAULT}"
  -e CUDA_VERSION="${CUDA_VERSION}"
  -e CUDA_SHORT="${CUDA_SHORT}"
  -e NODE_MAJOR="${NODE_MAJOR}"
  -v "${PROJECT_DIR}:/workspace/${PROJECT_NAME}:rw"
  -v "${CONTAINER_HOME_CACHE_DIR}:${CONTAINER_HOME}:rw"
  -v "${CACHE_DIR}:${CONTAINER_CACHE_DIR}:rw"
  -v "${NPM_GLOBAL_DIR}:${CONTAINER_NPM_GLOBAL_DIR}:rw"
  -v "${HOST_PROJ_MODEL_DIR}:${CONTAINER_PROJ_MODEL_DIR}:rw"
  -v /etc/passwd:/etc/passwd:ro
  -v /etc/group:/etc/group:ro
  -w "/workspace/${PROJECT_NAME}"
)

if [ "${ENABLE_FUSE}" = "1" ]; then
  if [ -e /dev/fuse ]; then
    docker_args+=(--device /dev/fuse:/dev/fuse)
  else
    echo "Warning: /dev/fuse is not present on the host; sshfs/FUSE inside the container may not work." >&2
  fi
  if [ "${FUSE_CAP_SYS_ADMIN}" = "1" ]; then
    docker_args+=(--cap-add SYS_ADMIN)
  fi
  if [ "${FUSE_APPARMOR_UNCONFINED}" = "1" ]; then
    docker_args+=(--security-opt apparmor:unconfined)
  fi
fi

if [ "${CONTAINER_LOGIN_USER}" = "root" ]; then
  docker_args+=(
    --user "0:${HOST_GID}"
    -e USER="root"
    -e LOGNAME="root"
  )
else
  docker_args+=(
    --user "${HOST_UID}:${HOST_GID}"
    -e USER="${HOST_USER}"
    -e LOGNAME="${HOST_USER}"
  )
fi

for group_id in $(id -G); do
  if [ "${group_id}" != "${HOST_GID}" ]; then
    docker_args+=(--group-add "${group_id}")
  fi
done

declare -A ADDED_MOUNTS=()
declare -a SYMLINK_SCAN_ROOTS=()
declare -a HOST_SHARED_PERMISSION_PATHS=(
  "/workspace/${PROJECT_NAME}"
  "${CONTAINER_HOME}"
  "${CONTAINER_CACHE_DIR}"
  "${CONTAINER_NPM_GLOBAL_DIR}"
  "${CONTAINER_PROJ_MODEL_DIR}"
)

add_host_shared_permission_path() {
  local target_path="$1"
  local existing

  [ -n "${target_path}" ] || return
  for existing in "${HOST_SHARED_PERMISSION_PATHS[@]}"; do
    [ "${existing}" != "${target_path}" ] || return
  done
  HOST_SHARED_PERMISSION_PATHS+=("${target_path}")
}

backup_conflicting_cache_target() {
  local cache_target="$1"
  local expected_type="$2"
  local backup_target

  if [ ! -e "${cache_target}" ] && [ ! -L "${cache_target}" ]; then
    return
  fi
  case "${expected_type}" in
    dir) [ -d "${cache_target}" ] && return ;;
    file) [ -f "${cache_target}" ] && return ;;
    *) echo "Unknown expected cache target type: ${expected_type}" >&2; exit 1 ;;
  esac

  backup_target="${cache_target}.mount-conflict-backup-$(date +%Y%m%d%H%M%S)-$$"
  echo "Backing up conflicting cached mount target: ${cache_target} -> ${backup_target}" >&2
  mv -- "${cache_target}" "${backup_target}"
}

prepare_container_home_target() {
  local target_path="$1"
  local source_real="$2"
  local relative_path
  local cache_target

  [[ "${target_path}" == "${CONTAINER_HOME}/"* ]] || return 0
  relative_path="${target_path#"${CONTAINER_HOME}/"}"
  cache_target="${CONTAINER_HOME_CACHE_DIR}/${relative_path}"

  mkdir -p "$(dirname -- "${cache_target}")"
  if [ -d "${source_real}" ]; then
    backup_conflicting_cache_target "${cache_target}" "dir"
    mkdir -p "${cache_target}"
  else
    backup_conflicting_cache_target "${cache_target}" "file"
    touch "${cache_target}"
  fi
}

add_mount_if_exists() {
  local source_path="$1"
  local target_path="$2"
  local mode="$3"
  local scan_symlinks="${4:-0}"
  local acl_recursive="${5:-}"
  local source_real
  local mount_key

  if [ ! -e "${source_path}" ]; then
    return
  fi

  source_real="$(readlink -f -- "${source_path}")"
  [ -n "${source_real}" ] && [ -n "${target_path}" ] || return

  mount_key="${source_real}=>${target_path}"
  if [ -n "${ADDED_MOUNTS[${mount_key}]:-}" ]; then
    return
  fi
  ADDED_MOUNTS["${mount_key}"]=1

  prepare_container_home_target "${target_path}" "${source_real}"
  if [[ ",${mode}," != *,ro,* ]]; then
    if [ -n "${acl_recursive}" ]; then
      grant_host_user_acl "${source_real}" "${acl_recursive}"
    elif path_is_under "${source_real}" "${HOST_HOME_REAL}"; then
      grant_host_user_acl "${source_real}" "0"
    else
      grant_host_user_acl "${source_real}"
    fi
  fi

  docker_args+=(-v "${source_real}:${target_path}:${mode}")
  if [[ ",${mode}," != *,ro,* ]]; then
    add_host_shared_permission_path "${target_path}"
  fi

  if [ "${scan_symlinks}" = "1" ] && [ -d "${source_real}" ]; then
    SYMLINK_SCAN_ROOTS+=("${source_real}")
  fi
}

add_shared_model_mounts_if_configured() {
  local IFS=":"
  local host_dirs=()
  local container_dirs=()
  local mounted_dirs=()
  local host_dir
  local source_real
  local container_dir
  local index=0
  local joined_dirs=""

  [ -n "${HOST_SHARED_MODEL_DIRS}" ] || return 0
  read -r -a host_dirs <<< "${HOST_SHARED_MODEL_DIRS}"
  if [ -n "${CONTAINER_SHARED_MODEL_DIRS}" ]; then
    read -r -a container_dirs <<< "${CONTAINER_SHARED_MODEL_DIRS}"
  fi

  for host_dir in "${host_dirs[@]}"; do
    [ -n "${host_dir}" ] || { index=$((index + 1)); continue; }
    if [ ! -d "${host_dir}" ]; then
      echo "Shared model dir not found; skipping: ${host_dir}" >&2
      index=$((index + 1))
      continue
    fi

    source_real="$(readlink -f -- "${host_dir}")"
    if [ -z "${source_real}" ]; then
      index=$((index + 1))
      continue
    fi

    container_dir="${container_dirs[${index}]:-}"
    if [ -z "${container_dir}" ]; then
      container_dir="${source_real}"
    fi

    add_mount_if_exists "${source_real}" "${container_dir}" "ro"
    mounted_dirs+=("${container_dir}")
    index=$((index + 1))
  done

  [ "${#mounted_dirs[@]}" -gt 0 ] || return 0
  for container_dir in "${mounted_dirs[@]}"; do
    joined_dirs="${joined_dirs}${joined_dirs:+:}${container_dir}"
  done
  docker_args+=(-e SHARED_MODEL_DIRS="${joined_dirs}")
  if [ "${#mounted_dirs[@]}" -eq 1 ]; then
    docker_args+=(-e SHARED_MODEL_DIR="${mounted_dirs[0]}")
  fi
}

container_path_for_host_path() {
  local host_path="$1"
  local relative_path

  if path_is_under "${host_path}" "${HOST_HOME_REAL}"; then
    relative_path="${host_path#"${HOST_HOME_REAL}"}"
    printf '%s%s\n' "${CONTAINER_HOME}" "${relative_path}"
  else
    printf '%s\n' "${host_path}"
  fi
}

is_agent_config_mount_path() {
  local path="$1"

  path_is_under "${path}" "${HOST_HOME_REAL}/.claude" ||
    path_is_under "${path}" "${HOST_HOME_REAL}/.codex" ||
    path_is_under "${path}" "${HOST_HOME_REAL}/.agents" ||
    path_is_under "${path}" "${HOST_HOME_REAL}/.orchestra"
}

skill_mount_root_for_path() {
  local path="$1"

  case "${path}" in
    */skills/*) printf '%s\n' "${path%%/skills/*}/skills" ;;
    */skills) printf '%s\n' "${path}" ;;
    *) return 1 ;;
  esac
}

add_symlink_skill_mount() {
  local link_path="$1"
  local raw_target
  local target_real
  local link_container_path
  local target_container_path
  local source_root
  local target_root

  raw_target="$(readlink -- "${link_path}")"
  target_real="$(readlink -f -- "${link_path}" 2>/dev/null || true)"
  if [ -z "${target_real}" ] || [ ! -e "${target_real}" ]; then
    echo "Skip broken skill symlink: ${link_path} -> ${raw_target}" >&2
    return
  fi
  if is_agent_config_mount_path "${target_real}"; then
    return
  fi
  source_root="$(skill_mount_root_for_path "${target_real}" || true)"
  [ -n "${source_root}" ] || return 0

  link_container_path="$(container_path_for_host_path "${link_path}")"
  if [[ "${raw_target}" = /* ]]; then
    target_container_path="${raw_target}"
  else
    target_container_path="$(realpath -m -- "$(dirname -- "${link_container_path}")/${raw_target}")"
  fi
  target_root="$(skill_mount_root_for_path "${target_container_path}" || true)"
  [ -n "${target_root}" ] || return 0

  add_mount_if_exists "${source_root}" "${target_root}" "${SKILL_SYMLINK_TARGET_MODE}" "1"
}

scan_registered_symlink_roots() {
  local scan_index=0
  local root
  local root_real
  local link_path
  declare -A SCANNED_ROOTS=()

  while [ "${scan_index}" -lt "${#SYMLINK_SCAN_ROOTS[@]}" ]; do
    root="${SYMLINK_SCAN_ROOTS[${scan_index}]}"
    scan_index=$((scan_index + 1))
    root_real="$(readlink -f -- "${root}" 2>/dev/null || true)"
    if [ -z "${root_real}" ] || [ -n "${SCANNED_ROOTS[${root_real}]:-}" ]; then
      continue
    fi
    SCANNED_ROOTS["${root_real}"]=1

    while IFS= read -r -d '' link_path; do
      add_symlink_skill_mount "${link_path}"
    done < <(find "${root_real}" -type l -print0 2>/dev/null)
  done
}

add_mount_if_exists "${HOST_NVIDIA_DIR}" "${CONTAINER_NVIDIA_DIR}" "ro,rshared"
add_mount_if_exists "${HOST_LOCAL_DIR}" "${CONTAINER_HOST_LOCAL_DIR}" "ro,rshared"
add_shared_model_mounts_if_configured

add_mount_if_exists "${HOST_HOME}/.claude" "${CONTAINER_HOME}/.claude" "${CLAUDE_CONFIG_MODE}" "1" "1"
add_mount_if_exists "${HOST_HOME}/.claude.json" "${CONTAINER_HOME}/.claude.json" "${CLAUDE_CONFIG_MODE}"
add_mount_if_exists "${HOST_HOME}/.codex" "${CONTAINER_HOME}/.codex" "${CODEX_CONFIG_MODE}" "1" "1"
add_mount_if_exists "${HOST_HOME}/.agents" "${CONTAINER_HOME}/.agents" "${AGENTS_CONFIG_MODE}"
add_mount_if_exists "${HOST_HOME}/.orchestra" "${CONTAINER_HOME}/.orchestra" "${ORCHESTRA_CONFIG_MODE}"
add_mount_if_exists "${HOST_PAPER_SKILLS_DIR}" "${CONTAINER_PAPER_SKILLS_DIR}" "ro" "1"
scan_registered_symlink_roots

join_by_colon() {
  local joined=""
  local item

  for item in "$@"; do
    [ -n "${item}" ] || continue
    joined="${joined}${joined:+:}${item}"
  done
  printf '%s\n' "${joined}"
}

HOST_SHARED_PERMISSION_PATHS_JOINED="$(join_by_colon "${HOST_SHARED_PERMISSION_PATHS[@]}")"
docker_args+=(
  -e HOST_UID="${HOST_UID}"
  -e HOST_GID="${HOST_GID}"
  -e HOST_USER="${HOST_USER}"
  -e HOST_GROUP="${HOST_GROUP}"
  -e HOST_SHARED_PERMISSION_REPAIR="${HOST_SHARED_PERMISSION_REPAIR}"
  -e HOST_SHARED_PERMISSION_PATHS="${HOST_SHARED_PERMISSION_PATHS_JOINED}"
)

docker "${docker_args[@]}" \
  "${IMAGE_NAME}" \
  bash -lc '
    set -euo pipefail
    umask 0002
    source /opt/conda/etc/profile.d/conda.sh

    fix_host_shared_permissions_once() {
      [ "$(id -u)" = "0" ] || return 0
      [ "${HOST_SHARED_PERMISSION_REPAIR:-1}" = "1" ] || return 0
      [ -n "${HOST_UID:-}" ] && [ -n "${HOST_GID:-}" ] || return 0

      local old_ifs="${IFS}"
      local path
      IFS=":"
      for path in ${HOST_SHARED_PERMISSION_PATHS:-}; do
        [ -n "${path}" ] && [ -e "${path}" ] || continue
        chown -h "${HOST_UID}:${HOST_GID}" "${path}" 2>/dev/null || true
        if [ -d "${path}" ]; then
          find "${path}" -xdev -uid 0 -exec chown -h "${HOST_UID}:${HOST_GID}" {} + 2>/dev/null || true
        fi
      done
      IFS="${old_ifs}"
    }

    select_cuda_runtime() {
      local requested="$1"
      local raw=""
      local cuda_version=""
      local cuda_home=""

      select_system_cuda() {
        if [ -d /usr/local/cuda ]; then
          cuda_home="/usr/local/cuda"
          return 0
        fi
        if [ -n "${CUDA_SHORT}" ] && [ -d "/usr/local/cuda-${CUDA_SHORT}" ]; then
          cuda_home="/usr/local/cuda-${CUDA_SHORT}"
          return 0
        fi
        cuda_home="$(find /usr/local -maxdepth 1 -type d -name "cuda-[0-9]*" -print 2>/dev/null | sort -V | tail -n 1 || true)"
        [ -n "${cuda_home}" ]
      }

      normalize_cuda_version() {
        raw="$1"
        raw="${raw#/usr/local/cuda-}"
        raw="${raw#cuda}"
        raw="${raw#cu}"
        raw="${raw#[._-]}"
        raw="${raw//_/.}"
        raw="${raw//-/.}"
        if [[ "${raw}" =~ ^([0-9]+)\.([0-9]+)$ ]]; then
          printf "%s.%s\n" "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"
          return 0
        fi
        if [[ "${raw}" =~ ^([0-9]{2})([0-9]+)$ ]]; then
          printf "%s.%s\n" "${BASH_REMATCH[1]}" "${BASH_REMATCH[2]}"
          return 0
        fi
        return 1
      }

      if [ -z "${requested}" ] || [ "${requested}" = "system" ] || [ "${requested}" = "default" ]; then
        if ! select_system_cuda; then
          echo "No default CUDA toolkit found under /usr/local." >&2
          exit 1
        fi
      elif [ -d "${requested}" ]; then
        cuda_home="${requested}"
      elif [ -f /opt/cuda-env.sh ] && source /opt/cuda-env.sh "${requested}"; then
        return 0
      else
        cuda_version="$(normalize_cuda_version "${requested}" || true)"
        if [ -n "${cuda_version}" ] && [ -d "/usr/local/cuda-${cuda_version}" ]; then
          cuda_home="/usr/local/cuda-${cuda_version}"
        else
          echo "Requested CUDA runtime is unavailable: ${requested}" >&2
          find /usr/local -maxdepth 1 -type d -name "cuda*" -printf "  %p\n" 2>/dev/null >&2 || true
          exit 1
        fi
      fi

      export CUDA_HOME="${cuda_home}"
      export PATH="${CUDA_HOME}/bin:${PATH}"
      export LD_LIBRARY_PATH="${CUDA_HOME}/lib64:${LD_LIBRARY_PATH:-}"
    }

    have_working_nodejs() {
      command -v node >/dev/null 2>&1 &&
        command -v npm >/dev/null 2>&1 &&
        node --version >/dev/null 2>&1 &&
        npm --version >/dev/null 2>&1
    }

    install_nodejs() {
      if have_working_nodejs; then
        return 0
      fi
      if [ "$(id -u)" != "0" ]; then
        echo "node/npm are not installed, and the container user cannot install Node.js." >&2
        exit 127
      fi
      if ! command -v apt-get >/dev/null 2>&1 || ! command -v curl >/dev/null 2>&1; then
        echo "node/npm are not installed, and apt-get/curl are unavailable for Node.js bootstrap." >&2
        exit 127
      fi
      echo "Installing Node.js ${NODE_MAJOR}.x for npm..."
      export DEBIAN_FRONTEND=noninteractive
      curl -fsSL "https://deb.nodesource.com/setup_${NODE_MAJOR}.x" -o /tmp/nodesource_setup.sh
      bash /tmp/nodesource_setup.sh
      apt-get install -y --no-install-recommends nodejs
      rm -f /tmp/nodesource_setup.sh
    }

    require_npm() {
      if have_working_nodejs; then
        return 0
      fi
      install_nodejs
      if ! have_working_nodejs; then
        echo "node/npm are still unavailable after attempting Node.js installation." >&2
        exit 127
      fi
    }

    have_chisel_http_ssh_deps() {
      command -v ssh >/dev/null 2>&1 &&
        command -v sshfs >/dev/null 2>&1 &&
        command -v fusermount3 >/dev/null 2>&1 &&
        command -v curl >/dev/null 2>&1 &&
        command -v gzip >/dev/null 2>&1
    }

    install_chisel_http_ssh_deps() {
      if have_chisel_http_ssh_deps; then
        return 0
      fi
      if [ "$(id -u)" != "0" ]; then
        echo "ssh/sshfs/FUSE tools are missing, and the container user cannot install packages." >&2
        exit 127
      fi
      if ! command -v apt-get >/dev/null 2>&1; then
        echo "ssh/sshfs/FUSE tools are missing, and apt-get is unavailable." >&2
        exit 127
      fi
      echo "Installing SSH, sshfs, and FUSE tools..."
      export DEBIAN_FRONTEND=noninteractive
      apt-get update
      apt-get install -y --no-install-recommends \
        ca-certificates \
        curl \
        fuse3 \
        gzip \
        iproute2 \
        kmod \
        openssh-client \
        procps \
        sshfs
    }

    ensure_npm_cli() {
      local package="$1"
      local binary="$2"

      require_npm
      if command -v "${binary}" >/dev/null 2>&1 && "${binary}" --version >/dev/null 2>&1; then
        return 0
      fi
      echo "Installing ${package}..."
      if npm install -g "${package}"; then
        hash -r
      fi
      if ! command -v "${binary}" >/dev/null 2>&1 || ! "${binary}" --version >/dev/null 2>&1; then
        echo "Failed to install required CLI: ${package} (${binary})" >&2
        exit 1
      fi
    }

    fix_host_shared_permissions_once
    select_cuda_runtime "${CUDA_DEFAULT}"
    install_chisel_http_ssh_deps
    mkdir -p "${XDG_CACHE_HOME}" "${NPM_CONFIG_PREFIX}"
    ensure_npm_cli @openai/codex@latest codex
    ensure_npm_cli @anthropic-ai/claude-code@latest claude
    fix_host_shared_permissions_once
    exec /bin/bash
  '
